### ISSUE TITLE
Opportunities to reduce repeated code

### ISSUE THREAD

**Issue by patdel0** [fac25/week-6_ASLP#27]
https://github.com/fac25/week-6_ASLP/blob/08ff021855257c5f88723766ae310e881de06516/components/addToBasketBtn.js#L14-L28

Whenever we find ourselves writing the same code more than once, it is usually a good indicator that there might be an opportunity to refactor.

**Comment by Abbbyccc** [comment]
very good suggestion. Thank you @patdel0 from the team
