### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by patdel0** [fac25/week-6_ASLP#29]
As a single quote, no trailing semi colon user, this config file looks awesome.
 https://github.com/fac25/week-6_ASLP/blob/08ff021855257c5f88723766ae310e881de06516/.prettierrc#L1-L6
![image](https://user-images.githubusercontent.com/53922624/198347510-71279204-a68c-4606-b6f3-e31314b2e99e.png)

**Comment by Abbbyccc** [comment]
credit to @mariapaz thank you!
